query PickupPoint($id: String!) @context(scope: "private") {
  pickupPoint(id: $id) {
    friendlyName
    id
    seller
    distance
    businessHours {
      openingTime
      closingTime
      dayOfWeek
    }
    address {
      id
      addressId
      street
      number
      receiverName
      complement
      neighborhood
      country
      state
      geoCoordinates
      postalCode
      city
      reference
      addressName
      addressType
    } 
  }
}
